# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py', 
    'GUI/__init__.py', 'GUI/admin_window.py', 'GUI/app.py', 'GUI/login_window.py', 
    'GUI/standard_user_window.py', 'GUI/widgets.py', 'GUI/styles.py',
    'managers/__init__.py', 'managers/db_manager.py', 'managers/xlsx_manager.py',
    'utils/logger.py'],
    pathex=[],
    binaries=[],
    # Only include app code and required non-Python files if any
    datas=[],
    hiddenimports=[
        'sqlite3', 
        'PyQt5', 
        'PyQt5.QtWidgets', 
        'PyQt5.QtCore', 
        'PyQt5.QtGui',
        'openpyxl',
        'openpyxl.cell',
        'openpyxl.chart',
        'openpyxl.chart.series',
        'openpyxl.chart.axis',
        'openpyxl.chart.data_source',
        'openpyxl.drawing',
        'openpyxl.drawing.image',
        'openpyxl.styles',
        'openpyxl.styles.borders',
        'openpyxl.styles.fills',
        'openpyxl.styles.fonts',
        'openpyxl.styles.colors',
        'openpyxl.styles.named_styles',
        'openpyxl.styles.numbers',
        'openpyxl.worksheet',
        'openpyxl.worksheet.datavalidation',
        'openpyxl.worksheet.formula',
        'openpyxl.worksheet.hyperlink',
        'openpyxl.worksheet.pagebreak',
        'openpyxl.worksheet.properties',
        'openpyxl.worksheet.table',
        'openpyxl.workbook',
        'openpyxl.workbook.external_link',
        'openpyxl.workbook.defined_name',
        'openpyxl.workbook.protection',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # Exclude tests and documentation/info files
    excludes=['tests', 'info'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Label Tracker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
